FROM debian:jessie
RUN apt update
RUN apt-get install -y git
RUN apt-get install -y autoconf automake
RUN apt-get install -y libboost-dev
RUN apt-get install -y g++
RUN apt-get install -y texinfo texlive
RUN apt-get install -y python
RUN apt-get install -y tcpdump
RUN apt-get install -y libtool make
RUN apt-get install -y build-essential devscripts apt-utils
RUN apt-get install -y libboost-coroutine-dev libboost-serialization-dev
RUN apt-get install -y libboost-system-dev

