FROM wye-fedora-dev
ARG GIT_VERSION=HEAD
RUN mkdir -p /usr/local/src/wye
WORKDIR /usr/local/src/wye
RUN git clone http://github.com/cybermaggedon/wye .; git checkout ${GIT_VERSION}
RUN git status
RUN autoreconf -i
RUN ./configure --prefix=/usr/local
RUN make check
RUN make -f pkg.mk rpm
