FROM wye-debian-dev
ARG GIT_VERSION=HEAD
RUN mkdir -p /usr/local/src/wye
WORKDIR /usr/local/src/wye
RUN git clone http://git.code.sf.net/p/wye/code .; git checkout ${GIT_VERSION}
RUN git status
RUN autoreconf -i
RUN ./configure --prefix=/usr/local
RUN make check
RUN make -f pkg.mk deb
